api = "0.5"

[buildpack]
  homepage = "https://github.com/paketo-buildpacks/go-mod-bom"
  id = "paketo-buildpacks/go-mod-bom"
  name = "Paketo Go Module Bill of Materials Generator Buildpack"

[metadata]
  include-files = ["bin/build", "bin/detect", "bin/run", "buildpack.toml"]
  pre-package = "./scripts/build.sh"

  [[metadata.dependencies]]
#    cpe = "cpe:2.3:a:owasp:cyclonedx-node-module:3.0.7:*:*:*:*:*:*:*"
    id = "cyclonedx-gomod"
#    licenses = ["Apache-2.0", "ECL-2.0", "SHL-0.51", "SHL-0.5"]
    name = "CycloneDX Go Module"
#    purl = "pkg:npm/%40cyclonedx/bom@3.0.7"
#    sha256 = "7974bf0e776c587c5e1ad44a7e75477ab5863ee037fd84f153727295ffd6d2cf"
#    source = "https://registry.npmjs.org/@cyclonedx/bom/-/bom-3.0.7.tgz"
#    source_sha256 = "da1b87cec24a2b029871254068c4cc575de15b6dcc3135e4c7019af898a5aa4c"
    stacks = ["io.buildpacks.stacks.bionic"]
#    uri = "https://deps.paketo.io/cyclonedx-node-module/cyclonedx-node-module_3.0.7_linux_x64_bionic_7974bf0e.tgz"
    #uri = "https://github.com/CycloneDX/cyclonedx-gomod/releases/download/v1.0.0/cyclonedx-gomod_1.0.0_linux_amd64.tar.gz"
#    uri = "file:///users/rdimsdale/Downloads/cyclonedx-gomod_1.0.0_linux_amd64.tar.gz"
#    sha256 = "9df5a4b9e290e364e78c43ea632034c1088f33a0afb0d6a96dc8e1d5d78171da"

    uri = "file:///users/bhenao/Downloads/cyclonedx-gomod_1.0.0_linux_amd64-repackage.tar.gz"
    sha256 = "7b96b57e678fa731f882627064cf9559590b033ba2155649450ae69c7f33688f"
    version = "1.0.0"

  [[metadata.dependency-constraints]]
    constraint = "*"
    id = "cyclonedx-gomod"
    patches = 1

[[stacks]]
  id = "io.buildpacks.stacks.bionic"
